name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: |
        cd react_app
        npm install

    - name: Build React app
      run: |
        cd react_app
        npm run build

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install autopep8
      run: |
        pip install autopep8

    - name: Collect static files
      env:
        DJANGO_SETTINGS_MODULE: EmploymentAssessment.settings
      run: |
        python manage.py collectstatic --noinput

    - name: Run autopep8
      run: |
        find . -name "*.py" | xargs autopep8 --in-place --aggressive --aggressive

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: EmploymentAssessment.settings
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Build React app
      run: |
        cd react_app
        npm run build

    - name: Deploy to Github Pages
      run: |
        cd react_app
        git init
        git add build
        git commit -m 'Deploy to Github Pages'
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/nkzarrabi/Employment-Assessment.git" master:gh-pages
