name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install autopep8 flake8 pytest pytest-django

    - name: Set environment variables
      run: |
        echo "PYTHONPATH=$(pwd)/Employment-Assessment" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=Employment-Assessment.settings" >> $GITHUB_ENV

    - name: Run autopep8
      run: |
        find . -name "*.py" | xargs autopep8 --in-place --aggressive --aggressive

    - name: Lint with flake8
      run: flake8 .

    - name: Run tests
      run: pytest
