name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Clear cache
      run: |
        rm -rf ~/.npm

    - name: Install Node.js dependencies
      run: |
        cd react_app
        npm install

    - name: Build React app
      run: |
        cd react_app
        npm run build

    - name: Verify Build Directory
      run: |
        ls -la react_app/build || echo "Build directory not found"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      env:
        DJANGO_SETTINGS_MODULE: EmploymentAssessment.settings
      run: |
        python manage.py collectstatic --noinput

    - name: Run Python formatting and linting
      run: |
        pip install autopep8 flake8
        find . -name "*.py" | xargs autopep8 --in-place --aggressive --aggressive
        flake8 .

    - name: Run Django tests
      env:
        DJANGO_SETTINGS_MODULE: EmploymentAssessment.settings
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: react_app/build
        force_orphan: true

